spring:
  batch:
    job:
      enabled: false # Prevent jobs to be executed at startup
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hiying
    password: hiying
    driver-class-name: oracle.jdbc.driver.OracleDriver
