spring:
  batch:
    job:
      enabled: false # Prevent jobs to be executed at startup
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hiying
    password: hiying
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  configuration:
    cache-enabled: false
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
  mapper-locations: mybatis-mappers/*Mapper.xml

integration:
  cron: 0 * * ? * * # every minute
  file-destination: src/filedump
